# Generated by Django 2.2.3 on 2019-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Answered')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
        ),
    ]
