# Generated by Django 2.2.3 on 2019-07-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='ques',
        ),
    ]
