# Generated by Django 2.2.3 on 2019-08-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
