# Generated by Django 2.2.3 on 2019-08-04 17:22

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190804_2239'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='blog',
    #         name='content',
    #         field=(verbose_name='Content'),
    #     ),
    #]
