# Generated by Django 2.2.3 on 2019-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='ques',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('sc', 'Science'), ('ls', 'Life Style')], default='Science', max_length=10),
        ),
    ]
