# Generated by Django 2.2.3 on 2019-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190710_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Science', 'Science'), ('Lifestyle', 'Life Style')], default='Science', max_length=10),
        ),
    ]
