# Generated by Django 2.2.3 on 2019-07-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_question_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='field',
        ),
    ]
