# Generated by Django 2.2.3 on 2019-07-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_remove_question_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
